package enums;

public enum StudentComparatorList {
    STUDENT_AVGEXAMSCORE_COMPARATOR,
    STUDENT_CURRENTCOURSENUMBER_COMPARATOR,
    STUDENT_FULLNAME_COMPARATOR,
    STUDENT_UNIVERSITYID_COMPARATOR
}
