package enums;

public enum UniversityComparatorList {
    UNIVERSITY_FULLNAME_COMPARATOR,
    UNIVERSITY_ID_COMPARATOR,
    UNIVERSITY_MAINPROFILE_COMPARATOR,
    UNIVERSITY_SHORTNAME_COMPARATOR,
    UNIVERSITY_YEAROFFOUNDATION_COMPARATOR
}
